version: "3"
services:
  db:
    platform: linux/x86_64
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - db-store:/var/lib/mysql
    environment:
      MYSQL_DATABASE: minpaku
      MYSQL_ROOT_PASSWORD: password
  redis:
    image: redis
    ports:
    - "6379:6379"
    command: redis-server --appendonly yes --requirepass foobared
volumes:
  db-store: